### ISSUE TITLE
removal of BFQ

### ISSUE THREAD

**Issue by torvic9** [hhoffstaette/kernel-patches#10]
Hi again Holger,
Can you tell me what bugs exactly led you to remove the BFQ patches? BFQ was still in 4.9.16, so I'm wondering if the bump to .17 introduced the bugs, or if they were always there and have just been discovered?
MfG

**Comment by hhoffstaette** [comment]
I also recently got the oops that was reported on the BFQ list and after reading about use-after-free bugs just got tired of trying to keep up with BFQ, patch-wise. The performance benefits of BFQ are vastly overrated and since I only have a single rotational drive with btrfs - which seems to confuse BFQ with its metadata redundancy and seems to have no better performance than with CFQ - I decided to ditch it..again. We'll see how BFQ fares when it's in mainline and gets a real workout..
Ultimately I prefer to have a not-so-optimal scheduler that doesn't crash than one with theoretical benefits but higher overhead and use-after-free bugs.
Btw for a likely-mostly-idle interactive system you'll likely get similar benefits and better response behaviour from smaller dirty writeback buffers, lower writeback interval, writeback throttling (needs to be enabled), plain more RAM and maybe deadline as I/O scheduler (ironic and "theoretically wrong", but true). I was thinking of enabling writeback throttling by default in the next release since it works so well.

If you insist you can always fetch the patches from git (or whatever is in BFQ mainline) and add them yourself. Again, sorry for the hassle.

**Comment by hhoffstaette** [comment]
I realise this was probably not what you wanted to hear but if it answers your question, please close this issue. Thanks. :)

**Comment by torvic9** [comment]
Thanks for the explanation! I'll keep an eye on it.
