### ISSUE TITLE
Xfs log throttle patch missing in 5.6 branch

### ISSUE THREAD

**Issue by disaster123** [hhoffstaette/kernel-patches#16]
Is there any reason why https://github.com/hhoffstaette/kernel-patches/blob/5.4/5.4/xfs-20191009-don't-allow-log-IO-to-be-throttled.patch is missing from 5.6 branch?

Stefan

**Comment by hhoffstaette** [comment]
Sorry for the delay, it seems Github's changes to notifications no longer send emails for issues.
I don't remember offhand why I dropped it from 5.6; it has been in mainline for a while now ([here](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/fs/xfs/xfs_log.c?id=2def2845cc33390e39b51440508043e4981e10ee)).
Since I switched to 5.7 some time ago and 5.6 is EOL I don't think there's anything I can still do here,
but thank you for the notice anyway.
